spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql}:3306/test?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${mysqlUser}
    password: ${mysqlPass}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
